### ISSUE TITLE
vatID

### ISSUE THREAD

**Issue by lucasseiixas** [azpay/Magento-2.x#3]
Olá, 

Mesmo com a atualização, o modulo segue com problemas no pagamento em relação ao cpf 

![image](https://user-images.githubusercontent.com/25618037/111197592-696c5880-859d-11eb-8e47-5effcd14f29a.png)

**Comment by azpay-dev** [comment]
Vamos ajustar a organização das versões baseado na versão do magento 2, nesse momento, o packgist está com a versão antiga ainda. Para ir adiantando você pode fazer o download do último commit.
